baseurl = "http://dicknaniel.github.io/educasa/"
languageCode = "en-us"
title = "educasa"
MetaDataFormat = "toml"
paginate = 10 # optional
copyright = "© 2015 <a href=\"http://mcbsnj.com\">mcbsnj</a>"

# [params]
#   author = "Your Name"
#   photo = "images/photo.png" # optional
#   profile = "images/profile.png" # optional
#   cover = "images/cover.png" # optional
#   twitter = "Your Twitter Name" # optional
#   github = "Your Github Name" # optional
#   facebook = "Your facebook Name" # optional
#   gplus = "Your Google+ Name" # optional
#   linkedin = "Your linkedin Name" # optional
#   googleAnalyticsUserID = "Your Analytics User Id" # optional

[permalinks]
  post = "/:year/:month/:day/:filename/" # optional

[taxonomies]
  tag = "tags" # singular = "plural"
  room = "rooms" # Which room the clip deals with
